CREATE TABLE sales(
id VARCHAR(200) PRIMARY KEY,
itemID VARCHAR (200) FOREIGN KEY REFERENCES products(id),
quantity INT,
orderID VARCHAR(200) FOREIGN KEY REFERENCES orders(id),
price DECIMAL(10,2) 
)
